CREATE DATABASE WEB_POKEDEX

USE WEB_POKEDEX

CREATE TABLE POKEMON(
	ID INT IDENTITY PRIMARY KEY,
	IDENTIFICACAO INT UNIQUE NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	ALCUNHO VARCHAR(30) NOT NULL,
	DESCRICAO VARCHAR(500),
	ALTURA VARCHAR(10),
	PESO VARCHAR(10)
);

/*Frescurinha de pokedex, mostar o local onde o pokemon aparece tipicamente*/
CREATE TABLE LOCAIS(
	ID INT IDENTITY PRIMARY KEY,
	LOCAL VARCHAR(50) NOT NULL,
	ID_POKEMON INT FOREIGN KEY REFERENCES POKEMON(ID)
);

CREATE TABLE TIPOS(
	ID INT IDENTITY PRIMARY KEY,
	TIPO VARCHAR(30) NOT NULL UNIQUE,
	POKEMON_ID INT FOREIGN KEY REFERENCES POKEMON(ID)
);

/*
Ó A EVOLUÇÃO
E V O L U Ç Ã O
*/
CREATE TABLE EVOLUCAO(
	ID_PRE_POKE INT FOREIGN KEY REFERENCES POKEMON(ID),
	ID_EVOLUIDO INT FOREIGN KEY REFERENCES POKEMON(ID)
);